sudo: required
services:
    - docker
jobs:
    fast_finish: true
    include:
        - name: "PHP 5.6, librdkafka 0.11.6"
          env: PHP_IMAGE_TAG=5.6-alpine LIBRDKAFKA_VERSION=v0.11.6 LIBSSL_VERSION=1.0
        - name: "PHP 5.6, librdkafka 1.0.1"
          env: PHP_IMAGE_TAG=5.6-alpine LIBRDKAFKA_VERSION=v1.0.1 LIBSSL_VERSION=1.0
        - name: "PHP 5.6, librdkafka 1.1.0"
          env: PHP_IMAGE_TAG=5.6-alpine LIBRDKAFKA_VERSION=v1.1.0 LIBSSL_VERSION=1.0
        - name: "PHP 5.6, librdkafka 1.2.2"
          env: PHP_IMAGE_TAG=5.6-alpine LIBRDKAFKA_VERSION=v1.2.2 LIBSSL_VERSION=1.0
        - name: "PHP 5.6, librdkafka 1.3.0"
          env: PHP_IMAGE_TAG=5.6-alpine LIBRDKAFKA_VERSION=v1.2.0 LIBSSL_VERSION=1.0
        - name: "PHP 5.6, librdkafka master"
          env: PHP_IMAGE_TAG=5.6-alpine LIBRDKAFKA_VERSION=master LIBSSL_VERSION=1.0
env:
    global:
        - TEST_KAFKA_BROKERS=localhost:9092
        - TEST_KAFKA_BROKER_VERSION=2.3
before_script:
    - ./.travis/start-kafka.sh
    - ./.travis/build-image.sh
script: 
    ### Issues with environmental variables causes this copy to be required
    - cp tests/test_env.php.sample tests/test_env.php
    - ./.travis/test.sh
