dist: xenial
language: php
php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
env:
    - LIBRDKAFKA_VERSION=0.11.x
    - LIBRDKAFKA_VERSION=v1.0.1
    - LIBRDKAFKA_VERSION=v1.1.0
    - LIBRDKAFKA_VERSION=master
script: ./travis.sh
