version: '3.2'

services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        PHP_IMAGE_TAG: 7.4-alpine
        LIBRDKAFKA_VERSION: v1.3.0
        LIBSSL_VERSION: 1.1
    tty: yes
    environment:
      TEST_KAFKA_BROKERS: kafka:9092
      TEST_KAFKA_BROKER_VERSION: 2.3
      TEST_PHP_EXECUTABLE: /usr/local/bin/php
    volumes:
      - ./:/php-rdkafka
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:5.3.2
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2182'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
